create type public.app_role as enum ('user', 'moderator', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 60),
  city text check (city is null or char_length(city) <= 100),
  bio text check (bio is null or char_length(bio) <= 200),
  favorite_position text check (
    favorite_position is null or
    favorite_position in ('Goalkeeper', 'Defender', 'Midfielder', 'Forward')
  ),
  skill_level text check (
    skill_level is null or
    skill_level in ('Casual', 'Intermediate', 'Baller', 'Open to All')
  ),
  avatar_url text check (avatar_url is null or char_length(avatar_url) <= 2048),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'user',
  created_at timestamptz not null default now()
);

create table public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 3 and 100),
  target_type text not null check (char_length(target_type) between 2 and 50),
  target_id text check (target_id is null or char_length(target_id) <= 128),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index audit_events_actor_created_idx
  on public.audit_events (actor_user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.audit_events enable row level security;

create policy "Users can read their own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Users can read their own role"
  on public.user_roles for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can read their own audit history"
  on public.audit_events for select
  to authenticated
  using ((select auth.uid()) = actor_user_id);

grant select, update on public.profiles to authenticated;
grant select on public.user_roles to authenticated;
grant select on public.audit_events to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(
      coalesce(
        nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
        split_part(coalesce(new.email, 'Player'), '@', 1)
      ),
      60
    )
  );

  insert into public.user_roles (user_id, role)
  values (new.id, 'user');

  insert into public.audit_events (
    actor_user_id,
    action,
    target_type,
    target_id
  )
  values (new.id, 'account.created', 'account', new.id::text);

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.audit_profile_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.audit_events (
    actor_user_id,
    action,
    target_type,
    target_id
  )
  values (new.id, 'profile.updated', 'profile', new.id::text);
  return new;
end;
$$;

create trigger on_profile_updated
  after update on public.profiles
  for each row execute procedure public.audit_profile_update();

